# 应用基础配置
spring:
  profiles:
    active: prod  # 默认使用开发环境
  application:
    name: ts-download-service
  # 文件上传
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

# MyBatis-Plus配置
mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: com.ts.download.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 全局配置
  global-config:
    db-config:
      # 主键类型 AUTO:"数据库ID自增"
      id-type: auto
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 禁用一级缓存
    local-cache-scope: statement
    # 禁用二级缓存
    cache-enabled: false

# Swagger配置
swagger:
  enabled: true
  title: TS文件下载服务API
  description: 提供文件下载地址生成功能
  version: 1.0.0
  base-package: com.ts.download.controller
